name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        uses: ferdnyc/gsconnect-ci@gh-action
        with:
          commands: >
            meson --prefix=/usr \
                  --libdir=lib/ \
                  -Dgnome_shell_libdir=/usr/lib64/ \
                  -Dpost_install=true \
                  _build

      - name: Uninstalled Tests
        uses: ferdnyc/gsconnect-ci@gh-action
        with:
          commands: >
            meson test -C _build --suite gsconnect:data \
                                 --suite gsconnect:lint \
                                 --print-errorlogs

      - name: Installed Tests
        uses: ferdnyc/gsconnect-ci@gh-action
        with:
          commands: >
            ninja -C _build install; \
            xvfb-run -a dbus-run-session -- \
            gnome-desktop-testing-runner gsconnect -L _build/meson-logs

      - name: Upload Test Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: _build/meson-logs

      - name: Test Build
        run: |
          ninja -C _build make-zip

      - name: Upload Test Build
        uses: actions/upload-artifact@v2
        with:
          name: test-build
          path: _build/gsconnect@andyholmes.github.io.zip

